name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        working-directory: kairos_api
        run: dotnet restore kairos.sln

      - name: Build
        working-directory: kairos_api
        run: dotnet build kairos.sln --configuration Release --no-restore

      - name: Run tests
        working-directory: kairos_api
        run: dotnet test kairos.sln --configuration Release --no-build
